# Generated by Django 5.2.12 on 2026-04-27 15:47

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Min


def merge_accepted_answers(apps, schema_editor):
    Answer = apps.get_model('questions', 'Answer')
    dupes = (
        Answer.objects.filter(is_accepted=True)
        .values('question_id')
        .annotate(n=Count('id'), keep=Min('id'))
        .filter(n__gt=1)
    )
    for row in dupes:
        Answer.objects.filter(
            question_id=row['question_id'],
            is_accepted=True,
        ).exclude(pk=row['keep']).update(is_accepted=False)


def merge_accepted_answers_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(merge_accepted_answers, merge_accepted_answers_reverse),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_accepted', True)), fields=('question',), name='questions_answer_one_accepted'),
        ),
        migrations.AddConstraint(
            model_name='answerlike',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='questions_alike_user_answer'),
        ),
        migrations.AddConstraint(
            model_name='questionlike',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='questions_qlike_user_question'),
        ),
    ]
