# Generated by Django 6.0.4 on 2026-05-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_answer_is_active_answerlike_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='рейтинг'),
        ),
    ]
